branches:
  - main
  - "hotfix/*"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: 'echo VERSION=\"${nextRelease.version}\" > .env'
