branches:
  - main
  - hotfix/*
  - feature/*
  - bugfix/*

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: "angular"
      releaseRules:
        - type: "chore"
          release: "patch"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: |
        export CURRENT_VERSION=$(node -p "require('./package.json').version")
        if [ -n "$GITHUB_ENV" ]; then
            echo "VERSION=$CURRENT_VERSION" >> "$GITHUB_ENV"
        else
            export VERSION=$CURRENT_VERSION
        fi
      verifyReleaseCmd: |
        export VERSION="${nextRelease.version}"

        if [ -n "$GITHUB_ENV" ]; then
            echo "VERSION=$VERSION" >> "$GITHUB_ENV"
        fi
