branches:
  - main
  - "hotfix/*"
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: "angular"
    - releaseRules:
        - type: "chore"
          release: "patch"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: >-
        echo VERSION="${nextRelease.version}" >> $GITHUB_ENV
