branches: 
  - main
  - hotfix/*
  - feature/*
  - bugfix/*

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: "angular"
      releaseRules:
        - type: "chore"
          release: "patch"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: |
        export VERSION="${nextRelease.version}"

        if [ ! -z $GITHUB_ENV ];
        then
          echo $VERSION >> $GITHUB_ENV
        fi