branches:
  - main

version_files:
  - Cargo.toml

changelog:
  file: CHANGELOG.md

commit_types:
  chore: patch

hooks:
  pre_release:
    - cargo test
    - cargo build --release
    - ./target/release/embed-it README.md
    - git add README.md action.yml example.yml
