name: "embed-md"
description: "A GitHub Action for the `embedme` node package."
branding:
  icon: "file"
  color: "gray-dark"
inputs:
  markdown-files:
    description: "The files where code should be embedded."
    required: false
    default: "README.md"
  commit-message:
    description: "The message to associate with the commit containing the modified markdown files."
    required: false
    default: "chore: embed code within markdown files"
  commit-name:
    description: "Define the name of the commit."
    required: false
    default: "github-actions[bot]"
  commit-author:
    description: "Define the author of the commit."
    required: false
    default: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
  commit-push:
    description: "Set to false when we want to skip the push."
    required: false
    default: "true"
  commit-dry:
    description: "Set to true when we want to skip the commit."
    required: false
    default: "false"
runs:
  using: "docker"
  image: urmzd/embed-md:1.3.4
  env:
    COMMIT_NAME: "${{ inputs.commit-name }}"
    COMMIT_EMAIL: "${{ inputs.commit-email }}"
    COMMIT_MESSAGE: "${{ inputs.commit-message }}"
    COMMIT_PUSH: "${{ inputs.commit-push }}"
    MARKDOWN_FILES: "${{ inputs.markdown-files }}"
    COMMIT_DRY: "${{ inputs.commit-dry }}"
