name: "embed-md"
description: "A GitHub Action for the `embedme` node package."
branding:
  icon: "code"
  color: "gray-dark"
inputs:
  markdown-files:
    description: "The files where code should be embedded."
    required: false
    default: "README.md"
  commit-message: 
    description: "The message to associate with the commit containing the modified markdown files." 
    required: false
    default: "chore: embed code within markdown files"
runs:
  using: 'docker'
  image: 'urmzd/embed-me:{{$VERSION}}'
  args:
    - '${{ inputs.commit-message }}'
    - "${{ inputs.markdown-files }}"

