name: "embed-md"
description: "A GitHub Action for the `embedme` node package."
branding:
  icon: "file"
  color: "gray-dark"
inputs:
  markdown-files:
    description: "The files where code should be embedded."
    required: false
    default: "README.md"
  commit-message:
    description: "The message to associate with the commit containing the modified markdown files."
    required: false
    default: "chore: embed code within markdown files"
  commit-author:
    description: "Define the author of the commit."
    required: false
    default: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
  commit-push:
    description: "Set to false when we want to skip the push."
    required: false
    default: "true"
runs:
  using: "docker"
    # TODO: Replace the capture group found in urmzd/embed-me:(.*) with the version merged into main.
  image: "urmzd/embed-me:1.0.3"
  env:
    COMMIT_AUTHOR: "${{ inputs.commit-author }}"
    COMMIT_MESSAGE: "${{ inputs.commit-message }}"
    COMMIT_PUSH: "${{ inputs.commit-push }}"
    MARKDOWN_FILES: "${{ inputs.markdown-files }}"
