[output]
dir = "./showcase"

[[output.formats]]
output_type = "png"

[[scenes]]
type = "markdown"
name = "before"
path = "showcase/demo/README.md"
theme = "dark"
full_page = true

[[scenes]]
type = "markdown"
name = "after"
path = "showcase/demo/README.after.md"
theme = "dark"
full_page = true
