name: "Example"

on: [release]

jobs:
  embed-example:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout current repo"
        uses: actions/checkout@v3
      - name: "Run entrypoint script."
        uses: urmzd/embed-md@v1.2.1
        id: "embed-code"
        with:
          markdown-files: "README.md"
          commit-message: "chore: embed example using self"
          commit-author: "Urmzd Mukhammadnaim <urmzd@noreply.com>"
          commit-push: "false"
