name: "Deployment"

on:
  workflow_run:
    workflows: ["Integration"]  # Name of your CI workflow
    branches: [main]
    types:
      - completed

jobs:
  deployment:
    runs-on: ubuntu-latest
    # The CD job should only run if the CI was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ">=20"
      - name: Install dependencies
        run: npm ci
      - name: Run commit analyzer
        run: npx semantic-release -d
      - name: Run action on self
        run: |
          docker run -v "$(pwd):/app" \
            -e COMMIT_MESSAGE="chore: this is an example commit message" \
            -e MARKDOWN_FILES="README.md" \
            -e PUSH="false" \
            -e COMMIT_AUTHOR="github-actions[bot] <github-actions[bot]@users.noreply.github.com>" \
            "urmzd/embed-md:${VERSION}"
      - name: "Update references"
        run: ./scripts/update_version_refs
      - name: "Update npm version"
        run: |
          # bump version if needed
          npm version --force ${VERSION}
      - name: "Do the release"
        run: |
          npx semantic-release
          