name: "Deployment"

on:
  workflow_run:
    workflows: ["Integration"]  # Name of your CI workflow
    branches: [main]
    types:
      - completed

jobs:
  deployment:
    runs-on: ubuntu-latest
    # The CD job should only run if the CI was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ">=20"
      - name: Install dependencies
        run: npm ci
      - name: Run commit analyzer
        run: npx semantic-release -d
      - name: Run action on self
        uses: ./
        with:
          commit-message: "chore(release): ${VERSION}"
          markdown-files: "README.md"
          push: "false"
      - name: "Update references"
        run: ./scripts/update_version_refs.sh
      - name: "Update npm version"
        continue-on-error: true
        run: |
          # bump version if needed
          npm version --force ${VERSION}
      - name: "Do the release"
        run: |
          npx semantic-release
          